name: Ping Supabase Function

on:
  schedule:
    # Every 15 minutes
    - cron: "*/15 * * * *"
  workflow_dispatch: # allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Supabase Endpoint
        run: |
          curl -s -o /dev/null -w "%{http_code}" \
          https://xypjqjegqnjooiclemkd.supabase.co/functions/v1/api/posts/4
