name: Ping Supabase Function

on:
  schedule:
    # Every Sunday at 00:00 UTC
    - cron: "0 0 * * 0"
    # Every Wednesday at 00:00 UTC
    - cron: "0 0 * * 3"
  workflow_dispatch: # allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Supabase Endpoint
        run: |
          curl -s -o /dev/null -w "%{http_code}" \
          https://xypjqjegqnjooiclemkd.supabase.co/functions/v1/api/posts/4
