name: Ping database to prevent the project from being paused

on:
  schedule:
    - cron: '5 18 * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ping database
        run: curl https://xypjqjegqnjooiclemkd.supabase.co/functions/v1/api/posts/4
        shell: zsh
